name: Coverage Statistics for laniw.com

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  test-coverage:
    name: Check Test Coverage
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x ]

    permissions:
      checks: write
      pull-requests: write
      contents: read

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3
      - name: Check Test Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm test