name: Lint laniw.com

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Run Prettier
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: -c "**/**.!(pdf|png|svg|afdesign)"
          prettier_plugins: prettier-plugin-svelte